# This file was automagically generated by mbed.org. For more information, 
# see http://mbed.org/handbook/Exporting-to-GCC-ARM-Embedded

GCC_BIN = 
PROJECT = people-counter
OBJECTS = ./lwip/tag/13/Core/lwIP/netif/loopif.o ./lwip/tag/13/Core/lwIP/netif/etharp.o ./lwip/tag/13/Core/lwIP/core/tcp_in.o ./lwip/tag/13/Core/lwIP/core/netif.o ./lwip/tag/13/Core/lwIP/core/memp.o ./lwip/tag/13/Core/lwIP/core/dns.o ./lwip/tag/13/Core/lwIP/core/pbuf.o ./lwip/tag/13/Core/lwIP/core/dhcp.o ./lwip/tag/13/Core/lwIP/core/raw.o ./lwip/tag/13/Core/lwIP/core/stats.o ./lwip/tag/13/Core/lwIP/core/sys.o ./lwip/tag/13/Core/lwIP/core/mem.o ./lwip/tag/13/Core/lwIP/core/udp.o ./lwip/tag/13/Core/lwIP/core/tcp_out.o ./lwip/tag/13/Core/lwIP/core/init.o ./lwip/tag/13/Core/lwIP/core/tcp.o ./lwip/tag/13/Core/lwIP/core/snmp/msg_in.o ./lwip/tag/13/Core/lwIP/core/snmp/msg_out.o ./lwip/tag/13/Core/lwIP/core/snmp/asn1_dec.o ./lwip/tag/13/Core/lwIP/core/snmp/mib_structs.o ./lwip/tag/13/Core/lwIP/core/snmp/asn1_enc.o ./lwip/tag/13/Core/lwIP/core/snmp/mib2.o ./lwip/tag/13/Core/lwIP/core/ipv4/autoip.o ./lwip/tag/13/Core/lwIP/core/ipv4/inet_chksum.o ./lwip/tag/13/Core/lwIP/core/ipv4/ip.o ./lwip/tag/13/Core/lwIP/core/ipv4/icmp.o ./lwip/tag/13/Core/lwIP/core/ipv4/inet.o ./lwip/tag/13/Core/lwIP/core/ipv4/ip_addr.o ./lwip/tag/13/Core/lwIP/core/ipv4/ip_frag.o ./lwip/tag/13/Core/lwIP/core/ipv4/igmp.o ./lwip/tag/13/Core/arch/iputil.o ./bigmath.o ./main.o ./lwip/tag/13/HTTPServer/HTTPServer.o ./lwip/tag/13/HTTPClient/HTTPClient.o ./lwip/tag/13/Core/TCPConnection.o ./lwip/tag/13/Core/NetServer.o ./lwip/tag/13/Core/TCPListener.o ./lwip/tag/13/Core/TCPItem.o ./lwip/tag/13/Core/lwIP/netif/device.o ./TextLCD/TextLCD.o 
SYS_OBJECTS = ./mbed/LPC1768/cmsis_nvic.o ./mbed/LPC1768/system_LPC17xx.o ./mbed/LPC1768/core_cm3.o ./mbed/LPC1768/stackheap.o ./mbed/LPC1768/startup_LPC17xx.o 
INCLUDE_PATHS = -I. -I./lwip -I./lwip/tag -I./lwip/tag/13 -I./lwip/tag/13/HTTPServer -I./lwip/tag/13/HTTPClient -I./lwip/tag/13/Core -I./lwip/tag/13/Core/lwIP -I./lwip/tag/13/Core/lwIP/netif -I./lwip/tag/13/Core/lwIP/core -I./lwip/tag/13/Core/lwIP/core/snmp -I./lwip/tag/13/Core/lwIP/core/ipv4 -I./lwip/tag/13/Core/lwIP/include -I./lwip/tag/13/Core/lwIP/include/netif -I./lwip/tag/13/Core/lwIP/include/lwip -I./lwip/tag/13/Core/lwIP/include/ipv4 -I./lwip/tag/13/Core/lwIP/include/ipv4/lwip -I./lwip/tag/13/Core/arch -I./mbed -I./mbed/LPC1768 -I./TextLCD 
LIBRARY_PATHS = 
LIBRARIES = 
LINKER_SCRIPT = None

############################################################################### 
AS      = $(GCC_BIN)arm-none-eabi-as
CC      = $(GCC_BIN)arm-none-eabi-gcc
CPP     = $(GCC_BIN)arm-none-eabi-g++
LD      = $(GCC_BIN)arm-none-eabi-gcc
OBJCOPY = $(GCC_BIN)arm-none-eabi-objcopy

CPU = -mcpu=cortex-m3 -mthumb
CC_FLAGS = $(CPU) -c -g -fno-common -fmessage-length=0 -Wall -fno-exceptions -ffunction-sections -fdata-sections 
CC_FLAGS += -MMD -MP
CC_SYMBOLS = -DTARGET_LPC1768 -DTARGET_M3 -DTARGET_NXP -DTARGET_LPC176X -DTARGET_MBED_LPC1768 -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -D__CORTEX_M3 -DARM_MATH_CM3 -DMBED_BUILD_TIMESTAMP=1406076420.82 -D__MBED__=1 

LD_FLAGS = -mcpu=cortex-m3 -mthumb -Wl,--gc-sections --specs=nano.specs -u _printf_float -u _scanf_float
LD_SYS_LIBS = -lstdc++ -lsupc++ -lm -lc -lgcc -lnosys

ifeq ($(DEBUG), 1)
  CC_FLAGS += -DDEBUG -O0
else
  CC_FLAGS += -DNDEBUG -Os
endif

all: $(PROJECT).bin

clean:
	rm -f $(PROJECT).bin $(PROJECT).elf $(OBJECTS) $(DEPS)

.s.o:
	$(AS) $(CPU) -o $@ $<

.c.o:
	$(CC)  $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu99   $(INCLUDE_PATHS) -o $@ $<

.cpp.o:
	$(CPP) $(CC_FLAGS) $(CC_SYMBOLS) -std=gnu++98 $(INCLUDE_PATHS) -o $@ $<


$(PROJECT).elf: $(OBJECTS) $(SYS_OBJECTS)
	$(LD) $(LD_FLAGS) -T$(LINKER_SCRIPT) $(LIBRARY_PATHS) -o $@ $^ $(LIBRARIES) $(LD_SYS_LIBS) $(LIBRARIES) $(LD_SYS_LIBS)

$(PROJECT).bin: $(PROJECT).elf
	$(OBJCOPY) -O binary $< $@

DEPS = $(OBJECTS:.o=.d) $(SYS_OBJECTS:.o=.d)
-include $(DEPS)
